name: PR pipeline
on:
  pull_request:
    branches: [main]
jobs:
  # As we extend the pipeline here are some useful references:
  # https://github.com/bluefireteam/audioplayers/blob/main/.github/workflows/build.yaml
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        flutterVersion: ['3.3.4']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Java (needed for android building)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutterVersion }}
          channel: 'stable'
          architecture: x64
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get

      - name: Run lint
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: dart analyze --fatal-infos

      - name: Install Flutter requirements for Linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Build linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          flutter config --enable-linux-desktop
          flutter build linux --release --obfuscate --split-debug-info=build/symbols/linux/v0.0.1
      - name: Build web
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: ./scripts/release-web.sh
      - name: Build android
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: ./scripts/release-android.sh

      - name: Build windows
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release --obfuscate --split-debug-info=build/symbols/linux/v0.0.1

      - name: Build macos
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          flutter config --enable-macos-desktop
          flutter build macos
      - name: Build ios
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: flutter build ios --release --no-codesign

      - name: Run tests
        run: dart test
